### PR TITLE
[WIP] feat: korean whole translation

### PR DESCRIPTION
**Pull request by HotoRas**
## What is this?
This is a whole translation of misskey hub website into Korean.

## Why did it?
I found some disabilities on English site, and Korean site is not provided even when they're translated quite much.
So, I decided to translate the entirity of the website.

## Contributors
@JeonDohyeon - Fork Owner, translated the entirity

### CODE REVIEW

**Comment by sjkim04** [comment]
hi please give me write access tank you

**Comment by sjkim04** [comment]
@JeonDohyeon

**Comment by HotoRas** [comment]
> hi please give me write access tank you

?

**Comment by sjkim04** [comment]
🤔🤔🤔

저에게 도와달라고 핑하신 거 아니었나요

edit: ㄱㅅ

**Comment by HotoRas** [comment]
얜 더미 PR입니다
쓰기 권한을 얻으시려면 여기에서 멘션 없이 절 협박하시면 됩니다 

얜 안 합치고 닫을 예정이니 자세한건 Upstream에서 확인해주세요

**Pull request closed without merging**
